import { Injectable } from '@angular/core';
import { MajorTournament, Tournament } from './types/Tournaments';

@Injectable({
  providedIn: 'root',
})
export class TournamentsService {
  constructor() {}

  getAllTournaments(): Tournament[] {
    // 1 open
    // 3 done
    return [
      {
        name: 'Gran Torneo',
        description:
          'Lorem ipsum odor amet, consectetuer adipiscing elit. Tempor posuere elementum ultrices sed orci posuere faucibus bibendum. Ex quam mi id finibus in felis volutpat. Blandit commodo tempus venenatis ultricies lobortis aliquet velit integer. Sed facilisi sem felis eget phasellus placerat. Quam adipiscing fringilla est urna habitasse.',
        ubication: 'Lugar 1, CDMX',
        participants: '85',
        date: '2024-12-31',
        imgUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733721996/lihwlh1p4xynviwwcikm.avif',
        game: 'League of Legends',
        status: 1,
        listParticipants: [
          'PewDiePie',
          'Ninja',
          'Shroud',
          'Pokimane',
          'Valkyrae',
          'Ibai Llanos',
          'AuronPlay',
          'TheGrefg',
          'Rubius',
          'TimTheTatman',
          'DrLupo',
          'Summit1g',
          'Myth',
          'Ludwig',
          'xQc',
          'Sykkuno',
          'Asmongold',
          'Nadeshot',
          'Nickmercs',
          'Amouranth',
          'Faker',
          's1mple',
          'TenZ',
          'Caps',
          'Rekkles',
          'karrigan',
          'Hiko',
          'Chovy',
          'Perkz',
          'Clix',
          'Bugha',
          'Mongraal',
          'Scump',
          'Coldzera',
          'KennyS',
          'GeT_RiGhT',
          'RamboRay',
          'Dendi',
          'Fatal1ty',
          'Daigo Umehara',
          'Tokido',
          'MKLeo',
          'Hungrybox',
          'ZeRo',
          'SonicFox',
          'ChocoTaco',
          'Disguised Toast',
          'Corpse Husband',
          'TommyInnit',
          'Technoblade',
        ],
      },
      {
        name: 'Super Torneo',
        description:
          'Lorem ipsum odor amet, consectetuer adipiscing elit. Tempor posuere elementum ultrices sed orci posuere faucibus bibendum. Ex quam mi id finibus in felis volutpat. Blandit commodo tempus venenatis ultricies lobortis aliquet velit integer. Sed facilisi sem felis eget phasellus placerat. Quam adipiscing fringilla est urna habitasse.',
        ubication: 'Lugar 5, Tijuana',
        participants: '1059',
        date: '2024-12-31',
        imgUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733722241/qglhfyux9aadnvedofkk.webp',
        game: 'Fornite',
        status: 1,
        listParticipants: [
          'PewDiePie',
          'Ninja',
          'Shroud',
          'Pokimane',
          'Valkyrae',
          'Ibai Llanos',
          'AuronPlay',
          'TheGrefg',
          'Rubius',
          'TimTheTatman',
          'DrLupo',
          'Summit1g',
          'Myth',
          'Ludwig',
          'xQc',
          'Sykkuno',
          'Asmongold',
          'Nadeshot',
          'Nickmercs',
          'Amouranth',
          'Faker',
          's1mple',
          'TenZ',
          'Caps',
          'Rekkles',
          'karrigan',
          'Hiko',
          'Chovy',
          'Perkz',
          'Clix',
          'Bugha',
          'Mongraal',
          'Scump',
          'Coldzera',
          'KennyS',
          'GeT_RiGhT',
          'RamboRay',
          'Dendi',
          'Fatal1ty',
          'Daigo Umehara',
          'Tokido',
          'MKLeo',
          'Hungrybox',
          'ZeRo',
          'SonicFox',
          'ChocoTaco',
          'Disguised Toast',
          'Corpse Husband',
          'TommyInnit',
          'Technoblade',
        ],
      },
      {
        name: 'Torneo Grande',
        description:
          'Lorem ipsum odor amet, consectetuer adipiscing elit. Tempor posuere elementum ultrices sed orci posuere faucibus bibendum. Ex quam mi id finibus in felis volutpat. Blandit commodo tempus venenatis ultricies lobortis aliquet velit integer. Sed facilisi sem felis eget phasellus placerat. Quam adipiscing fringilla est urna habitasse.',
        ubication: 'Cualquier Lugar, Sonora',
        participants: '185',
        date: '2024-12-01',
        imgUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733722305/qfiewmfkuaqd8j4mokkf.webp',
        game: 'Counter Strike 2',
        status: 3,
        listParticipants: [
          'PewDiePie',
          'Ninja',
          'Shroud',
          'Pokimane',
          'Valkyrae',
          'Ibai Llanos',
          'AuronPlay',
          'TheGrefg',
          'Rubius',
          'TimTheTatman',
          'DrLupo',
          'Summit1g',
          'Myth',
          'Ludwig',
          'xQc',
          'Sykkuno',
          'Asmongold',
          'Nadeshot',
          'Nickmercs',
          'Amouranth',
          'Faker',
          's1mple',
          'TenZ',
          'Caps',
          'Rekkles',
          'karrigan',
          'Hiko',
          'Chovy',
          'Perkz',
          'Clix',
          'Bugha',
          'Mongraal',
          'Scump',
          'Coldzera',
          'KennyS',
          'GeT_RiGhT',
          'RamboRay',
          'Dendi',
          'Fatal1ty',
          'Daigo Umehara',
          'Tokido',
          'MKLeo',
          'Hungrybox',
          'ZeRo',
          'SonicFox',
          'ChocoTaco',
          'Disguised Toast',
          'Corpse Husband',
          'TommyInnit',
          'Technoblade',
        ],
      },
      {
        name: 'Torneo Demasiado Grande',
        description:
          'Lorem ipsum odor amet, consectetuer adipiscing elit. Tempor posuere elementum ultrices sed orci posuere faucibus bibendum. Ex quam mi id finibus in felis volutpat. Blandit commodo tempus venenatis ultricies lobortis aliquet velit integer. Sed facilisi sem felis eget phasellus placerat. Quam adipiscing fringilla est urna habitasse.',
        ubication: 'Lugar Grande, Sinaloa',
        participants: '984',
        date: '2024-12-31',
        imgUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733722346/moe4pmcjtu2h7zhb2hsy.webp',
        game: 'Free Fire',
        status: 1,
        listParticipants: [
          'PewDiePie',
          'Ninja',
          'Shroud',
          'Pokimane',
          'Valkyrae',
          'Ibai Llanos',
          'AuronPlay',
          'TheGrefg',
          'Rubius',
          'TimTheTatman',
          'DrLupo',
          'Summit1g',
          'Myth',
          'Ludwig',
          'xQc',
          'Sykkuno',
          'Asmongold',
          'Nadeshot',
          'Nickmercs',
          'Amouranth',
          'Faker',
          's1mple',
          'TenZ',
          'Caps',
          'Rekkles',
          'karrigan',
          'Hiko',
          'Chovy',
          'Perkz',
          'Clix',
          'Bugha',
          'Mongraal',
          'Scump',
          'Coldzera',
          'KennyS',
          'GeT_RiGhT',
          'RamboRay',
          'Dendi',
          'Fatal1ty',
          'Daigo Umehara',
          'Tokido',
          'MKLeo',
          'Hungrybox',
          'ZeRo',
          'SonicFox',
          'ChocoTaco',
          'Disguised Toast',
          'Corpse Husband',
          'TommyInnit',
          'Technoblade',
        ],
      },
      {
        name: 'Torneo 33',
        description:
          'Lorem ipsum odor amet, consectetuer adipiscing elit. Tempor posuere elementum ultrices sed orci posuere faucibus bibendum. Ex quam mi id finibus in felis volutpat. Blandit commodo tempus venenatis ultricies lobortis aliquet velit integer. Sed facilisi sem felis eget phasellus placerat. Quam adipiscing fringilla est urna habitasse.',
        ubication: 'Lugar 33, Durango',
        participants: '333',
        date: '2024-12-31',
        imgUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733722384/jgayawvevkel2cgu91lm.jpg',
        game: 'Fornite',
        status: 1,
        listParticipants: [
          'PewDiePie',
          'Ninja',
          'Shroud',
          'Pokimane',
          'Valkyrae',
          'Ibai Llanos',
          'AuronPlay',
          'TheGrefg',
          'Rubius',
          'TimTheTatman',
          'DrLupo',
          'Summit1g',
          'Myth',
          'Ludwig',
          'xQc',
          'Sykkuno',
          'Asmongold',
          'Nadeshot',
          'Nickmercs',
          'Amouranth',
          'Faker',
          's1mple',
          'TenZ',
          'Caps',
          'Rekkles',
          'karrigan',
          'Hiko',
          'Chovy',
          'Perkz',
          'Clix',
          'Bugha',
          'Mongraal',
          'Scump',
          'Coldzera',
          'KennyS',
          'GeT_RiGhT',
          'RamboRay',
          'Dendi',
          'Fatal1ty',
          'Daigo Umehara',
          'Tokido',
          'MKLeo',
          'Hungrybox',
          'ZeRo',
          'SonicFox',
          'ChocoTaco',
          'Disguised Toast',
          'Corpse Husband',
          'TommyInnit',
          'Technoblade',
        ],
      },
      {
        name: 'Gran Torneo 44',
        description:
          'Lorem ipsum odor amet, consectetuer adipiscing elit. Tempor posuere elementum ultrices sed orci posuere faucibus bibendum. Ex quam mi id finibus in felis volutpat. Blandit commodo tempus venenatis ultricies lobortis aliquet velit integer. Sed facilisi sem felis eget phasellus placerat. Quam adipiscing fringilla est urna habitasse.',
        ubication: 'Lugar 44, Nuevo Leon',
        participants: '444',
        date: '2024-12-31',
        imgUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733722415/bwtkwqi17vy1yil1k01v.jpg',
        game: 'Street Fighter',
        status: 1,
        listParticipants: [
          'PewDiePie',
          'Ninja',
          'Shroud',
          'Pokimane',
          'Valkyrae',
          'Ibai Llanos',
          'AuronPlay',
          'TheGrefg',
          'Rubius',
          'TimTheTatman',
          'DrLupo',
          'Summit1g',
          'Myth',
          'Ludwig',
          'xQc',
          'Sykkuno',
          'Asmongold',
          'Nadeshot',
          'Nickmercs',
          'Amouranth',
          'Faker',
          's1mple',
          'TenZ',
          'Caps',
          'Rekkles',
          'karrigan',
          'Hiko',
          'Chovy',
          'Perkz',
          'Clix',
          'Bugha',
          'Mongraal',
          'Scump',
          'Coldzera',
          'KennyS',
          'GeT_RiGhT',
          'RamboRay',
          'Dendi',
          'Fatal1ty',
          'Daigo Umehara',
          'Tokido',
          'MKLeo',
          'Hungrybox',
          'ZeRo',
          'SonicFox',
          'ChocoTaco',
          'Disguised Toast',
          'Corpse Husband',
          'TommyInnit',
          'Technoblade',
        ],
      },
    ];
  }

  getMajorTournaments(): MajorTournament[] {
    return [
      {
        imageUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733618426/byj9y4ep0fdsuolz4r5o.jpg',
      },
      {
        imageUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733706867/hbnoh8jjznxssplkhhq3.jpg',
      },
      {
        imageUrl:
          'https://res.cloudinary.com/dqhqif9sw/image/upload/v1733706866/g1f5zcphxrytohwlg10k.avif',
      },
    ];
  }
}
